# --- REUSUABLE CHUNKS ---
clone: &clone
  checkout:
    path: /cammis-helm

job_setup: &job_setup
  docker:
    - image: cadhcscammis/infrastructure-private:PAT-163
  environment:
    GIT_REPO_PATH: /cammis-helm
    CHART_SRC_PATH: /cammis-helm/apps
    HELM_REPO_URL: https://ca-mmis.github.io/cammis-helm

  working_directory: /ci_job

add_helm_repo: &add_helm_repo
  run:
    name: Add CA-MMIS Helm Repo
    command: helm repo add cammis ${HELM_REPO_URL}

master_commits_only: &master_commits_only
  filters:
    branches:
      only: master

move_package_into_helm_repo: &move_package_into_helm_repo
  run:
    name: Move package into Helm repo
    command: mv *.tgz ${GIT_REPO_PATH}/.

reindex_helm_repo: &reindex_helm_repo
  run:
    name: Re-index Helm Repo
    command: helm repo index ${GIT_REPO_PATH} --url ${HELM_REPO_URL}

remove_leftover_apps_dir: &remove_leftover_apps_dir
  run:
    name: Remove leftover apps dir
    command: rm -rf ${GIT_REPO_PATH}/apps

switch_to_helm_repo_branch: &switch_to_helm_repo_branch
  run:
    name: Switch Git repo to Helm repo
    command: git -C ${GIT_REPO_PATH} checkout gh-pages

# ---- JOBS ---
version: 2
jobs:
  build_hello_cammis_data:
    <<: *job_setup
    steps:
      - <<: *clone
      - <<: *add_helm_repo
      - run:
          name: Update dependencies
          command: helm dep up ${CHART_SRC_PATH}/hello-cammis-data
      - run:
          name: Build Chart
          command: helm package ${CHART_SRC_PATH}/hello-cammis-data
      - <<: *switch_to_helm_repo_branch
      - <<: *remove_leftover_apps_dir
      - <<: *move_package_into_helm_repo
      - <<: *reindex_helm_repo


# --- WORKFLOWS ---
workflows:
  version: 2
  master_push:
    jobs:
      - build_hello_cammis_data:
          <<: *master_commits_only
