apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service
  labels:
    app: {{.Chart.Name}}
spec:
  type: LoadBalancer
  ports:
    - port: {{.Values.hello_cammis.port}}
      targetPort: {{.Values.hello_cammis.port}}
      protocol: TCP
  selector:
    app: {{.Chart.Name}}