apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deploy
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-pod
          image: cadhcscammis/{{.Chart.Name}}:{{.Chart.Version}}
          ports:
            - containerPort: {{.Values.hello_cammis_data.port}}
      livenessProbe:
        initialDelaySeconds: 10
        periodSeconds: 60
        timeoutSeconds: 2
        failureThreshold: 5
        successThreshold: 1
        httpGet:
          path: /alive
          port: {{.Values.hello_cammis_data.port}}
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 60
        timeoutSeconds: 2
        failureThreshold: 5
        successThreshold: 1
        httpGet:
          path: /ready
          port: {{.Values.hello_cammis_data.port}}